
CREATE TABLE IF NOT EXISTS calendar_notes (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL, uid UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(), date TIMESTAMPTZ NOT NULL DEFAULT now(), title TEXT NOT NULL, note TEXT 
);
