
CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL, title TEXT UNIQUE NOT NULL, description TEXT , done BOOLEAN NOT NULL DEFAULT false, uid UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4()
);
